### ISSUE TITLE
Levels Compatibility

### ISSUE THREAD

**Issue by theripper93** [David-Zvekic/TokensVisible#19]
Hello , i'm the dev for the module Levels - i would like to work out some compatibility, feel free to reach out on discord theripper93#3276

**Comment by David-Zvekic** [comment]
I'm having trouble figuring out whether the modules are actually
incompatible, because I am not sure how to use levels and how to build a
good test case to demonstrate a problem.

YTV seems to be compatible with Walls now.

To start, I'll refactor Tokens Visible vision logic into stand alone
discrete methods with names that reflect the settings.
Then I'll call my new methods from inside my overrides and wrappers rather
than implement more than 1 rule in the same wrapper.  It might be easier to
make some progress.
The wrappers are currently written as they are to mirror the organization
of the Foundry Core. I didn't like that organization but I thought it might
be easiest if someone wants to send a pull request.

After this refactor then other module developers could access the YTV
vision logic to cause their module to automatically reflect the vision
choices the GM made in YTV.  Or selectively turn that logic off, override
it or wrap it if their module creates a context where that may be useful.

The only thing I've confirmed is that if Levels is installed, when the GM
makes a token 'hidden' the player sees himself as if he is unhidden rather
than a translucent ghost that the GM sees. So the player has no feedback
confirming his token is hidden.     But I suspect maybe there are issues
with hidden tokens casting light that Levels might want to make the light
go away ..  I'm not sure.

I'll do my refactor first and if you can find a simple test case that
cleanly shows an incompatibility we can look at it.  I think since Levels
is more complex you may know of a specific example of a problem already.

If we need to share a stream or discuss verbally we can use discord, but
email is better for me to keep written communications sorted out.

Regards

David Zvekic

**Comment by theripper93** [comment]
For now the only blatant issue i can see when taking a  stair the token flies off into the distance before going to the correct position. You can test this in the test map provided in Levels. All this happens with YTV settings turned as off\default as possible

**Comment by David-Zvekic** [comment]
This included scene is excellent.  I'll play with it with YTV off for a bit
as a player in a separate browser to get a handle on the intended behavior.

**Comment by theripper93** [comment]
perfect, let me know if you need to know something or if you need me to do something on my end

**Comment by David-Zvekic** [comment]
to me it seems that if I turn off Sight Calculation Cache and set Ray
Casting mode to Standard (which is not the default for YTV)
then both modules appear to work together.

I noticed a remaining very minor issue if a player turns off token vision
animation and the GM drags them to a layered part of the map the layer may
obstruct their view unless they retake control of their token.

does that seem to be the case for you as well?

**Comment by theripper93** [comment]
that might be the case even without YTV - are you not having the issue of the token flying off when you drag move a token into a stair?

**Comment by David-Zvekic** [comment]
If I use:
Ray Casting Precision Mode : Standard
Sight Calculation Cache : OFF

then I dont get that behavior.   The scene appears very playable and usable
and I can login as a player and the GM can make me invisible and emitting
light, and I can walk around the map everywhere and climb stairs and go
inside the building and everything seems to work.

You can toggle both these settings without going back to the settings page
by pressing e, or E, so its easy to experiment.

foundry 0.8.8
system : alienrpg 2.0.1
YTV 2.5.1
wall height 3.5.3.8
levels 1.0
better roofs 0.9.3.5

maybe under a different system it malfunctions more severely?  it could be
a 3-way incompatibility.  In the above settings it seems to work very well.

There is 1 other very inconsequential behavior.  if the GM makes a players
token 'hidden', then the player wont see their token become translucent
unless they are controlling or hovering their cursor on their token.
Without levels, their hidden token always appears translucent.

can you confirm that using the settings above solves all the serious issues?

if it breaks under another system then I should look at it in the other
system.

**Comment by David-Zvekic** [comment]
I did notice a bug in Levels where if a token is emitting light and climbs
stairs, the light turns off temporarily.  but this isn't related to YTV, it
behaves that way whether or not YTV is present.

**Comment by theripper93** [comment]
so, first token emitting lights have weird behavious sometime thats a known issue, second the token not showing as translucent is expcted (i know why it happens but i won't worry too much about it) 

The token flying off however still happens even with the settings you provided, you are also on a pretty old version of levels\br

i'm on dnd5e

That ssaid token attacher also has the same exact issue so maybe that dev could shed some insight on why it's happening

**Comment by David-Zvekic** [comment]
I can't replicate the token flying off the screen. I'm using with Levels
1.2.4 now.

Ray Casting Precision Mode : Standard
Sight Calculation Cache : OFF

foundry 0.8.8
system : alienrpg 2.0.1
YTV 2.5.1
wall height 3.5.3.8
levels 1.2.4
better roofs 0.9.3.5

Only issues that I have is:   if the GM makes a players token 'hidden' with
YTV the expected behavior is the token should be translucent for the
player. With levels sometimes the token appears solid implying to the
player than they have become visible.   So far in my testing it looks like
the token is actually hidden even though it appears solid.

My only idea is that it is working for me randomly because of the order
that the various modules are loading.

In debugger it comes up as:



I have this:
Foundry VTT | Reestablishing existing session 8c292dd40c942bce966fa6b6
foundry.js:4085 Foundry VTT | Connected to server socket using session
8c292dd40c942bce966fa6b6
libWrapper-api.js:596 libWrapper 1.7.3.0 (d6bac10): Ready.
foundry.js:4188 Foundry VTT | Initializing Foundry Virtual Tabletop Game
alienrpg.js:40 Initializing Alien RPG
(anonymous) @ alienrpg.js:40
_call @ VM1633:4
callAll @ foundry.js:153
initialize @ foundry.js:4190
🎁call_wrapped @ libWrapper-wrapper.js:465
🎁libWrapperInit @ libWrapper-api.js:599
🎁Game.prototype.initialize#0 @ libWrapper-wrapper.js:160
window.addEventListener.once @ foundry.js:53180
async function (async)
window.addEventListener.once @ foundry.js:53179

*LEVELS STARTS UP*
libWrapper-api.js:425 libWrapper: Registered a wrapper for
'Token.prototype.refresh' by module 'levels' with type OVERRIDE.
libWrapper-api.js:425 libWrapper: Registered a wrapper for
'Token.prototype._onMovementFrame' by module 'levels' with type OVERRIDE.
libWrapper-api.js:425 libWrapper: Registered a wrapper for
'LightingLayer.prototype.refresh' by module 'levels' with type OVERRIDE.
libWrapper-api.js:425 libWrapper: Registered a wrapper for
'SightLayer.prototype.testVisibility' by module 'levels' with type OVERRIDE.
libWrapper-api.js:425 libWrapper: Registered a wrapper for
'WallsLayer.prototype.getRayCollisions' by module 'levels' with type
OVERRIDE.
libWrapper-api.js:425 libWrapper: Registered a wrapper for
'WallsLayer.prototype.checkCollision' by module 'levels' with type OVERRIDE.
libWrapper-api.js:425 libWrapper: Registered a wrapper for
'AmbientSound.prototype.isAudible' by module 'levels' with type OVERRIDE.
libWrapper-api.js:425 libWrapper: Registered a wrapper for
'MeasuredTemplate.prototype.draw' by module 'levels' with type OVERRIDE.
libWrapper-api.js:425 libWrapper: Registered a wrapper for
'Token.prototype.isVisible' by module 'levels' with type OVERRIDE.
libWrapper-api.js:425 libWrapper: Registered a wrapper for
'Token.prototype.checkCollision' by module 'levels' with type OVERRIDE.
*YOUR TOKENS VISIBLE STARTS UP*
TokensVisible.js:86 TokensVisible | Initializing Your Tokens Visible
libWrapper-api.js:425 libWrapper: Registered a wrapper for
'CanvasAnimation.animateLinear' by module 'TokensVisible' with type WRAPPER.
libWrapper-api.js:425 libWrapper: Registered a wrapper for
'Token.prototype._onUpdate' by module 'TokensVisible' with type WRAPPER.
libWrapper-api.js:425 libWrapper: Registered a wrapper for
'Wall.prototype._onUpdate' by module 'TokensVisible' with type WRAPPER.
libWrapper-api.js:425 libWrapper: Registered a wrapper for
'Token.prototype.isVisible' by module 'TokensVisible' with type WRAPPER.
libWrapper-api.js:425 libWrapper: Registered a wrapper for
'Token.prototype._isVisionSource' by module 'TokensVisible' with type
OVERRIDE.
libWrapper-api.js:425 libWrapper: Registered a wrapper for
'Token.prototype.setPosition' by module 'TokensVisible' with type OVERRIDE.
libWrapper-api.js:425 libWrapper: Registered a wrapper for
'Token.prototype.updateSource' by module 'TokensVisible' with type OVERRIDE.
*COLORSETTINGS*
colorSetting.js:608 ColorSettings | initializing
*WALL-HEIGHT*
libWrapper-api.js:425 libWrapper: Registered a wrapper for
'Token.prototype.updateSource' by module 'wall-height' with type WRAPPER.
libWrapper-api.js:425 libWrapper: Registered a wrapper for
'Token.prototype._onUpdate' by module 'wall-height' with type WRAPPER.
foundry.js:1457 Foundry VTT | Synchronized official game time in 31ms
foundry.js:3591 Foundry VTT | Retrieved and compiled template
systems/alienrpg/templates/actor/tabs/actor-inventory.html
foundry.js:3591 Foundry VTT | Retrieved and compiled template
systems/alienrpg/templates/actor/tabs/vehicle-inventory.html
foundry.js:3591 Foundry VTT | Retrieved and compiled template
systems/alienrpg/templates/actor/tabs/actor-systems.html
foundry.js:3494 Foundry VTT | Loaded localization file lang/en.json
foundry.js:3494 Foundry VTT | Loaded localization file
modules/TokensVisible/lang/en.json
foundry.js:3494 Foundry VTT | Loaded localization file
modules/betterroofs/lang/en.json
foundry.js:3494 Foundry VTT | Loaded localization file
modules/colorsettings/lang/en.json
foundry.js:3494 Foundry VTT | Loaded localization file
modules/levels/lang/en.json
foundry.js:3494 Foundry VTT | Loaded localization file
modules/turnAlert/lang/en.json
foundry.js:3494 Foundry VTT | Loaded localization file
modules/wall-height/lang/en.json
foundry.js:3494 Foundry VTT | Loaded localization file
systems/alienrpg/lang/en.json
foundry.js:2033 Foundry VTT | Rendering SceneNavigation
foundry.js:2033 Foundry VTT | Rendering Notifications
foundry.js:2033 Foundry VTT | Rendering Sidebar
foundry.js:2033 Foundry VTT | Rendering PlayerList
foundry.js:2033 Foundry VTT | Rendering Hotbar
foundry.js:2033 Foundry VTT | Rendering Pause
foundry.js:2033 Foundry VTT | Rendering SceneControls
foundry.js:3591 Foundry VTT | Retrieved and compiled template
templates/hud/navigation.html
foundry.js:4442 Foundry VTT | Document fonts loaded and ready
utils.min.js:8
    PixiJS 6.0.4 - ✰ WebGL 2 ✰      http://www.pixijs.com/    ♥♥♥
foundry.js:15480 Foundry VTT | Viewing Scene Baileywiki The Town - Farm
(Levels Demo)
foundry.js:17480 Foundry VTT | Drawing game canvas for scene Baileywiki The
Town - Farm (Levels Demo)
foundry.js:3591 Foundry VTT | Retrieved and compiled template
templates/sidebar/sidebar.html
foundry.js:2033 Foundry VTT | Rendering ActorDirectory
foundry.js:2033 Foundry VTT | Rendering ChatLog
foundry.js:2033 Foundry VTT | Rendering CombatTracker
foundry.js:2033 Foundry VTT | Rendering CompendiumDirectory
foundry.js:2033 Foundry VTT | Rendering ItemDirectory
foundry.js:2033 Foundry VTT | Rendering JournalDirectory
foundry.js:2033 Foundry VTT | Rendering PlaylistDirectory
foundry.js:2033 Foundry VTT | Rendering SceneDirectory
foundry.js:2033 Foundry VTT | Rendering Settings
foundry.js:2033 Foundry VTT | Rendering RollTableDirectory
foundry.js:3591 Foundry VTT | Retrieved and compiled template
templates/user/players.html
foundry.js:3591 Foundry VTT | Retrieved and compiled template
templates/hud/hotbar.html
foundry.js:3591 Foundry VTT | Retrieved and compiled template
templates/hud/pause.html
foundry.js:3591 Foundry VTT | Retrieved and compiled template
templates/hud/controls.html
*SOME MORE WRAPPERS PROBABLE NOT RELEVANT*
libWrapper-api.js:425 libWrapper: Registered a wrapper for
'SettingsConfig.prototype._onClickSubmenu' by module 'colorsettings' with
type OVERRIDE.
libWrapper-api.js:425 libWrapper: Registered a wrapper for
'Combat.prototype.createEmbeddedDocuments' by module 'TokensVisible' with
type WRAPPER.
foundry.js:3591 Foundry VTT | Retrieved and compiled template
templates/sidebar/actors-directory.html
foundry.js:3591 Foundry VTT | Retrieved and compiled template
templates/sidebar/chat-log.html
foundry.js:35153 Foundry VTT | Loaded
modules/levels/sample-maps/baileywiki/outhouse01-roof.webp (2%)
foundry.js:3591 Foundry VTT | Retrieved and compiled template
templates/sidebar/combat-tracker.html
foundry.js:3591 Foundry VTT | Retrieved and compiled template
templates/sidebar/compendium-directory.html
foundry.js:3591 Foundry VTT | Retrieved and compiled template
templates/sidebar/items-directory.html
foundry.js:3591 Foundry VTT | Retrieved and compiled template
templates/sidebar/journal-directory.html
foundry.js:3591 Foundry VTT | Retrieved and compiled template
templates/sidebar/playlists-directory.html
foundry.js:3591 Foundry VTT | Retrieved and compiled template
templates/sidebar/scenes-directory.html
foundry.js:3591 Foundry VTT | Retrieved and compiled template
templates/sidebar/settings.html
foundry.js:3591 Foundry VTT | Retrieved and compiled template
templates/sidebar/tables-directory.html
foundry.js:3591 Foundry VTT | Retrieved and compiled template
templates/sidebar/chat-message.html
foundry.js:35153 Foundry VTT | Loaded
modules/levels/sample-maps/baileywiki/barn-roof.webp (3%)
foundry.js:35153 Foundry VTT | Loaded
modules/levels/sample-maps/baileywiki/barn-shed-roof.webp (5%)
foundry.js:3591 Foundry VTT | Retrieved and compiled template
templates/dice/tooltip.html
foundry.js:35153 Foundry VTT | Loaded
modules/levels/sample-maps/baileywiki/park-treetop2.webp (6%)
foundry.js:35153 Foundry VTT | Loaded
modules/levels/sample-maps/baileywiki/park-treetop1.webp (8%)
foundry.js:35153 Foundry VTT | Loaded
modules/levels/sample-maps/baileywiki/park-treetop1.webp (9%)
foundry.js:35153 Foundry VTT | Loaded
modules/levels/sample-maps/baileywiki/barn-lvl2.webp (11%)
foundry.js:3591 Foundry VTT | Retrieved and compiled template
templates/dice/roll.html
foundry.js:35153 Foundry VTT | Loaded
modules/levels/sample-maps/baileywiki/basement03-block.webp (12%)
foundry.js:35153 Foundry VTT | Loaded
modules/levels/sample-maps/baileywiki/farmhouse-lvl2.webp (14%)
foundry.js:35153 Foundry VTT | Loaded
modules/levels/sample-maps/baileywiki/farmhouse-lvl2.webp (15%)
foundry.js:35153 Foundry VTT | Loaded
modules/levels/sample-maps/baileywiki/farmhouse-roof-combined.webp (17%)
foundry.js:35153 Foundry VTT | Loaded
modules/levels/sample-maps/baileywiki/basement01-block.webp (18%)
foundry.js:35153 Foundry VTT | Loaded icons/svg/combat.svg (20%)
foundry.js:35153 Foundry VTT | Loaded icons/svg/aura.svg (21%)
foundry.js:35153 Foundry VTT | Loaded icons/svg/mystery-man.svg (23%)
foundry.js:35153 Foundry VTT | Loaded icons/svg/mystery-man.svg (24%)
foundry.js:35153 Foundry VTT | Loaded icons/svg/mystery-man.svg (26%)
foundry.js:35153 Foundry VTT | Loaded icons/svg/padlock.svg (27%)
foundry.js:35153 Foundry VTT | Loaded icons/svg/up.svg (29%)
foundry.js:35153 Foundry VTT | Loaded icons/svg/down.svg (30%)
foundry.js:35153 Foundry VTT | Loaded icons/svg/skull.svg (32%)
foundry.js:35153 Foundry VTT | Loaded icons/svg/skull.svg (33%)
foundry.js:35153 Foundry VTT | Loaded icons/svg/cowled.svg (35%)
foundry.js:35153 Foundry VTT | Loaded icons/svg/light-off.svg (36%)
foundry.js:35153 Foundry VTT | Loaded icons/svg/light.svg (38%)
foundry.js:35153 Foundry VTT | Loaded icons/svg/sound.svg (39%)
foundry.js:35153 Foundry VTT | Loaded icons/svg/explosion.svg (41%)
foundry.js:35153 Foundry VTT | Loaded
modules/alienrpg-corerules/images/tokens/adultstage-v-neomorph-token.png
(42%)
foundry.js:35153 Foundry VTT | Loaded
modules/levels/sample-maps/baileywiki/farmhouse-lvl1.webp (44%)
foundry.js:35153 Foundry VTT | Loaded icons/svg/door-open-outline.svg (45%)
foundry.js:35153 Foundry VTT | Loaded
modules/levels/sample-maps/baileywiki/farmhouse-crops.webp (47%)
foundry.js:35153 Foundry VTT | Loaded icons/svg/door-locked-outline.svg
(48%)
foundry.js:35153 Foundry VTT | Loaded icons/svg/door-closed-outline.svg
(50%)
foundry.js:35153 Foundry VTT | Loaded icons/svg/door-secret-outline.svg
(52%)
foundry.js:35153 Foundry VTT | Loaded icons/svg/sound-off.svg (53%)
foundry.js:35153 Foundry VTT | Loaded icons/svg/sleep.svg (55%)
foundry.js:35153 Foundry VTT | Loaded icons/svg/net.svg (56%)
foundry.js:35153 Foundry VTT | Loaded icons/svg/daze.svg (58%)
foundry.js:35153 Foundry VTT | Loaded icons/svg/falling.svg (59%)
foundry.js:35153 Foundry VTT | Loaded icons/svg/paralysis.svg (61%)
foundry.js:35153 Foundry VTT | Loaded icons/svg/wing.svg (62%)
foundry.js:35153 Foundry VTT | Loaded icons/svg/deaf.svg (64%)
foundry.js:35153 Foundry VTT | Loaded icons/svg/blind.svg (65%)
foundry.js:35153 Foundry VTT | Loaded icons/svg/terror.svg (67%)
foundry.js:35153 Foundry VTT | Loaded icons/svg/silenced.svg (68%)
foundry.js:35153 Foundry VTT | Loaded icons/svg/unconscious.svg (70%)
foundry.js:35153 Foundry VTT | Loaded icons/svg/frozen.svg (71%)
foundry.js:35153 Foundry VTT | Loaded icons/svg/lightning.svg (73%)
foundry.js:35153 Foundry VTT | Loaded icons/svg/acid.svg (74%)
foundry.js:35153 Foundry VTT | Loaded icons/svg/blood.svg (76%)
foundry.js:35153 Foundry VTT | Loaded icons/svg/biohazard.svg (77%)
foundry.js:35153 Foundry VTT | Loaded icons/svg/radiation.svg (79%)
foundry.js:35153 Foundry VTT | Loaded icons/svg/fire.svg (80%)
foundry.js:35153 Foundry VTT | Loaded icons/svg/upgrade.svg (82%)
foundry.js:35153 Foundry VTT | Loaded icons/svg/poison.svg (83%)
foundry.js:35153 Foundry VTT | Loaded icons/svg/regen.svg (85%)
foundry.js:35153 Foundry VTT | Loaded icons/svg/downgrade.svg (86%)
foundry.js:35153 Foundry VTT | Loaded icons/svg/degen.svg (88%)
foundry.js:35153 Foundry VTT | Loaded icons/svg/ice-shield.svg (89%)
foundry.js:35153 Foundry VTT | Loaded icons/svg/target.svg (91%)
foundry.js:35153 Foundry VTT | Loaded icons/svg/eye.svg (92%)
foundry.js:35153 Foundry VTT | Loaded icons/svg/fire-shield.svg (94%)
foundry.js:35153 Foundry VTT | Loaded icons/svg/sun.svg (95%)
foundry.js:35153 Foundry VTT | Loaded icons/svg/angel.svg (97%)
foundry.js:35153 Foundry VTT | Loaded icons/svg/holy-shield.svg (98%)
foundry.js:35153 Foundry VTT | Loaded icons/svg/mage-shield.svg (100%)
foundry.js:54202 Foundry VTT | Delaying load of sound
modules/levels/sample-maps/baileywiki/Rath-Rain_Distant_Thunder_And_Bird_Loop.ogg
until after first user gesture
foundry.js:54202 Foundry VTT | Delaying load of sound
https://sound-effects-media.bbcrewind.co.uk/mp3/NHU05035029.mp3 until after
first user gesture
2foundry.js:54202 Foundry VTT | Delaying load of sound
modules/levels/sample-maps/baileywiki/fire-flames-crackle.ogg until after
first user gesture
foundry.js:2033 Foundry VTT | Rendering HeadsUpDisplay
foundry.js:3591 Foundry VTT | Retrieved and compiled template
templates/hud/hud.html
*LEVELS WELCOME MESSAGE*
ui.js:855 LEVELSWelcome to the 3rd Dimension
setupHandler.js:3
***************************************************************
setup @ setupHandler.js:3
(anonymous) @ alienrpg.js:217
_call @ VM1633:4
callAll @ foundry.js:153
setupGame @ foundry.js:4307
async function (async)
setupGame @ foundry.js:4284
_initializeGameView @ foundry.js:5117
_initializeView @ foundry.js:5093
initialize @ foundry.js:4202
async function (async)
initialize @ foundry.js:4196
🎁call_wrapped @ libWrapper-wrapper.js:465
🎁libWrapperInit @ libWrapper-api.js:599
🎁Game.prototype.initialize#0 @ libWrapper-wrapper.js:160
window.addEventListener.once @ foundry.js:53180
async function (async)
window.addEventListener.once @ foundry.js:53179
setupHandler.js:4 AlienRPGSetup Directories and tables
setup @ setupHandler.js:4
(anonymous) @ alienrpg.js:217
_call @ VM1633:4
callAll @ foundry.js:153
setupGame @ foundry.js:4307
async function (async)
setupGame @ foundry.js:4284
_initializeGameView @ foundry.js:5117
_initializeView @ foundry.js:5093
initialize @ foundry.js:4202
async function (async)
initialize @ foundry.js:4196
🎁call_wrapped @ libWrapper-wrapper.js:465
🎁libWrapperInit @ libWrapper-api.js:599
🎁Game.prototype.initialize#0 @ libWrapper-wrapper.js:160
window.addEventListener.once @ foundry.js:53180
async function (async)
window.addEventListener.once @ foundry.js:53179
setupHandler.js:5
***************************************************************
setup @ setupHandler.js:5
(anonymous) @ alienrpg.js:217
_call @ VM1633:4
callAll @ foundry.js:153
setupGame @ foundry.js:4307
async function (async)
setupGame @ foundry.js:4284
_initializeGameView @ foundry.js:5117
_initializeView @ foundry.js:5093
initialize @ foundry.js:4202
async function (async)
initialize @ foundry.js:4196
🎁call_wrapped @ libWrapper-wrapper.js:465
🎁libWrapperInit @ libWrapper-api.js:599
🎁Game.prototype.initialize#0 @ libWrapper-wrapper.js:160
window.addEventListener.once @ foundry.js:53180
async function (async)
window.addEventListener.once @ foundry.js:53179
foundry.js:2033 Foundry VTT | Rendering Dialog
alienrpg.js:242 needMigration false 2.0.0
(anonymous) @ alienrpg.js:242
async function (async)
(anonymous) @ alienrpg.js:217
_call @ VM1633:4
callAll @ foundry.js:153
setupGame @ foundry.js:4307
async function (async)
setupGame @ foundry.js:4284
_initializeGameView @ foundry.js:5117
_initializeView @ foundry.js:5093
initialize @ foundry.js:4202
async function (async)
initialize @ foundry.js:4196
🎁call_wrapped @ libWrapper-wrapper.js:465
🎁libWrapperInit @ libWrapper-api.js:599
🎁Game.prototype.initialize#0 @ libWrapper-wrapper.js:160
window.addEventListener.once @ foundry.js:53180
async function (async)
window.addEventListener.once @ foundry.js:53179
devmsg.js:24 latestVersion after 7
foundry.js:3591 Foundry VTT | Retrieved and compiled template
templates/hud/dialog.html
foundry.js:3591 Foundry VTT | Retrieved and compiled template
templates/app-window.html
foundry.js:53688 Foundry VTT | Activating pending audio playback with user
gesture.




I added some bold comments where I saw the modules loading.     Does it
load in the same order for you?
I can't replicate the problem (token flying off) you are reporting.

If the load order is different for you, then maybe we can figure out a way
to force the modules to load in a specific order?

David

**Comment by theripper93** [comment]
Mmm, i thought I fixed the token transparency, I’ll have a second look. Modules are loading in the same order, afaik they always load alphabetically. I also have another user having this issue. Again ,this is also an issue with token attached but only some people have it. I’ll try to investigate further

**Comment by uniwars** [comment]
Hi, I use YTV and levels and also get the flying thing

The flying thing is when dragging the token (not moving with arrow keys) onto a level's stair (like the ladder in the sample map) and the longer the drag the longer the token will see the roof instead of the second floor before returning to normal view.

Would that be possible to have an option to deactivate all features and be able to activate only the "z" key to push back a token, seeing invisible owned token and cut token animation when moving through wall ?

**Comment by David-Zvekic** [comment]
Based on this new description I understand what you are describing and I
was able to replicate it. I could make it extremely easy to see by setting
Token Animation Speed to 1 in YTV and then you have plenty of time to see
the animation out of place.

Issue was a bug in YTV. Specifically that 'CanvasAnimation.animateLinear'
returns a promise and my wrapper didn't return it.

The issue appears to be resolved. Please check YTV 2.5.2 and confirm when
you have time.

**Comment by uniwars** [comment]
I updated levels and YTV at last version and now each drag n drop of a token makes the vision refresh in a very quick loop, it's kinda very buggy and I still get my token sky rocketed when taking the stair after a drag n drop

here is a gif of the issue I get : https://gifyu.com/image/BvHE

**Comment by theripper93** [comment]
update to 1.3.1 i issued an hotfix a couple of minuts ago and check again please

**Comment by uniwars** [comment]
didn't change anything for me

**Comment by theripper93** [comment]
did you disable all other modules, it's working fine on my end

**Comment by uniwars** [comment]
after testing the conflict comes from drag ruler

**Comment by theripper93** [comment]
I guess that's a different issue then, i'll close this, check if the conflict is levels+drag ruler and i'll try to work something out
